#spring:
#  application:
#    name: department-service
#  config:
#    import: "optional:configserver:http://localhost:8088"

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${server.1}
    instance-id: ${server.1}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

#management:
#  tracing:
#    sampling:
#      probability: 1.0
